version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    restart: always
    command: start-dev
    ports:
      - 8081:8080
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem
    volumes:
      - $PWD/certs/server.crt.pem:/opt/keycloak/conf/server.crt.pem
      - $PWD/certs/server.key.pem:/opt/keycloak/conf/server.key.pem





