server:
  port: ${PORT:0}
  servlet:
    context-path: /hr-payroll

spring:
  application:
    name: hr-payroll
    version: 1.0.0 # Versão do aplicativo
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    statusPageUrlPath: /hr-payroll/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,refresh # Habilitar apenas os endpoints desejados

openapi:
  service:
    title: Payroll Microservice doc
    version: 1.0.0
    url: http://localhost:8765/hr-payroll #api gateway url
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html