server:
  port: ${PORT:0}
spring:
  application:
    name: hr-payroll
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

