server:
  port: ${PORT:0}
  servlet:
    context-path: /hr-worker

spring:
  profiles:
    active: test
  config:
    import: configserver:http://localhost:8888
  application:
    name: hr-worker
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD} 
    url: jdbc:postgresql://localhost:5432/hr-worker
    username: ${DATABASE_USERNAME} 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh # Habilitar apenas os endpoints desejados
