server:
  port: 8765
  servlet:
    context-path: /

logging:
  file:
    name: ./logs/log-file.log
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouterDefinitionLocator: INFO
        security: trace

issuer: http://localhost:9090/realms/ms-course
client-id: admin-rest-client
client-secret: 7pdk5UkU4DdfvCZZ0oVw9qXXRHG5dXx5
client-uri: http://localhost:9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: hr-api-gateway # Nome do aplicativo
    version: 1.0.0 # Versão do aplicativo
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
          jwk-set-uri: ${issuer}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**

        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**

        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/hr-user/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      #      this config is for api-gateway swagger-ui
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /hr-user/v3/api-docs
        name: User Service
      - url: /hr-worker/v3/api-docs
        name: Worker Service
      - url: /hr-payroll/v3/api-docs
        name: Payroll Service

