server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hr-worker
          uri: lb://hr-worker # hr-worker é o nome do serviço registrado no Eureka
          predicates:
            - Path=/api/workers/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/api/payments/**
