server:
  port: 8765
  servlet:
    context-path: /


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouterDefinitionLocator: INFO
        security: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: hr-api-gateway # Nome do aplicativo
    version: 1.0.0 # Versão do aplicativo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8443/realms/ms-course/protocol/openid-connect/certs
        client:
          provider:
            keycloak:
              issuer-uri: https://localhost:8443/realms/ms-course
          registration:
            spring-with-test-scope:
              provider: keycloak
              client-id: admin-rest-client
              client-secret: NFOpCliOcgXnqRfZ68zheEIIJ2YcTtWc
              authorization-grant-type: client_credentials
              scope: openid
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**

        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**

        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/hr-user/**

        - id: hr-oauth
          uri: lb://hr-oauth
          predicates:
            - Path=/hr-oauth/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      #      this config is for api-gateway swagger-ui
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /hr-user/v3/api-docs
        name: User Service
      - url: /hr-worker/v3/api-docs
        name: Worker Service
      - url: /hr-payroll/v3/api-docs
        name: Payroll Service

