server:
  port: ${PORT:0}

spring:
  application:
    name: hr-oauth
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
