server:
  port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/rodrigolim/ms-course-configs
          username: ${GIT_USER}
          password: ${GIT_PASS}
          fail-fast: true
