server:
  port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/${GIT_USER}/${GIT_REPOSITORY}
          username: ${GIT_USER}
          password: ${GIT_PASS}
          fail-fast: true

logging:
  level:
    org:
      springframework:
        security: trace