server:
  port: 8761
spring:
  application:
    name: hr-eureka-server
eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    instance:
      hostname: localhost # Em produção Especifique o hostname (eureka.example.com) ou endereço IP de produção
logging:
  level:
    org:
      springframework:
        security: trace